FROM postgres

MAINTAINER Fredy Ramos (fredy.rx@gmail.com)

ENV POSTGRES_PASSWORD postgres

ENV POSTGRES_USER postgres

ENV PGDATA /var/lib/postgresql/data/pgdata

ENV POSTGRES_DB movilidadDB

EXPOSE 5434